export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const POST_NEW_PRODUCT = "POST_NEW_PRODUCT";
export const GET_DETAIL = "GET_DETAIL";
export const GET_PRODUCT_FILTER = "GET_PRODUCT_FILTER"
export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const ADD_FAV = "ADD_FAV";
export const DELETE_FAV = "DELETE_FAV";
export const ADD_CART= "ADD_CART";
export const DELETE_CART = "DELETE_CART";
